name: ci

on:
  push:
    paths:
    - "**.py"

jobs:

  lint:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        py: ['3.7', '3.x']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.py }}

    - run: pip install .[lint]

    - run: flake8
    - run: mypy
